### ISSUE TITLE
Stopping TCPIP on zOS causes possible infinite looping error

### ISSUE THREAD

**Issue by armstrongibm** [zowe/explorer-server#29]
Hi,

**Versions:**
Zowe 0.9.4
zOS 2.3

**Situation:**
I stopped TCPIP running on my system(I appreciate that's an unusual thing to do, but it is required, especially on test / dev systems where Zowe may be running).

When I stopped TCPIP, Zowe started complaining (fair enough) - but once TCPIP was brought back up, the complaining didn't stop.

From what I can tell, there is a looping connection somewhere, which simply doesn't stop trying to reach a specific endpoint. It is worth noting that when TCPIP was brought down, a number of the running jobs under the main Zowe process also terminated (and I bet the ones which fell over, were supplying the endpoint in the looping error).

Please see a snippet of the looping error below:

```
Caused by: java.net.ConnectException: EDC8128I Connection refused. (Connection refused)
	at java.net.Socket.connect(Socket.java:666) ~Ýna:1.8.0¨
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:339) ~Ýhttpclient-4.5.6.jar!/:4.5.6¨
	at com.netflix.discovery.shared.transport.jersey.SSLSocketFactoryAdapter.connectSocket(SSLSocketFactoryAdapter.java:59) ~Ýeureka-client-1.9.3.jar!/:1.9.3¨
	at org.apache.http.conn.ssl.SSLSocketFactory.connectSocket(SSLSocketFactory.java:414) ~Ýhttpclient-4.5.6.jar!/:4.5.6¨
	at org.apache.http.impl.conn.DefaultClientConnectionOperator.openConnection(DefaultClientConnectionOperator.java:180) ~Ýhttpclient-4.5.6.jar!/:4.5.6¨
	at org.apache.http.impl.conn.AbstractPoolEntry.open(AbstractPoolEntry.java:144) ~Ýhttpclient-4.5.6.jar!/:4.5.6¨
	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:134) ~Ýhttpclient-4.5.6.jar!/:4.5.6¨
	at org.apache.http.impl.client.DefaultRequestDirector.tryConnect(DefaultRequestDirector.java:610) ~Ýhttpclient-4.5.6.jar!/:4.5.6¨
	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:445) ~Ýhttpclient-4.5.6.jar!/:4.5.6¨
	at org.apache.http.impl.client.AbstractHttpClient.doExecute(AbstractHttpClient.java:835) ~Ýhttpclient-4.5.6.jar!/:4.5.6¨
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:118) ~Ýhttpclient-4.5.6.jar!/:4.5.6¨
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56) ~Ýhttpclient-4.5.6.jar!/:4.5.6¨
	at com.sun.jersey.client.apache4.ApacheHttpClient4Handler.handle(ApacheHttpClient4Handler.java:173) ~Ýjersey-apache-client4-1.19.1.jar!/:1.19.1¨
	... 10 common frames omitted
 
2018-12-05 14:48:58.921 ERROR 65881 --- Ý7445-Acceptor-0¨ org.apache.tomcat.util.net.NioEndpoint   : Socket accept failed
 
java.io.IOException: EDC5122I Input/output error.
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~Ýna:1.8.0¨
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:478) ~Ýna:1.8.0¨
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:287) ~Ýna:1.8.0¨
	at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:455) ~Ýtomcat-embed-core-8.5.32.jar!/:8.5.32¨
	at java.lang.Thread.run(Thread.java:795) Ýna:2.9 (09-01-2017)¨
 
2018-12-05 14:48:58.940 ERROR 16843103 --- Ý7446-Acceptor-0¨ org.apache.tomcat.util.net.NioEndpoint   : Socket accept failed
 
java.io.IOException: EDC5122I Input/output error.
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~Ýna:1.8.0¨
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:478) ~Ýna:1.8.0¨
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:287) ~Ýna:1.8.0¨
	at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:482) ~Ýtomcat-coyote-8.5.33.jar!/:8.5.33¨
	at java.lang.Thread.run(Thread.java:795) Ýna:2.9 (09-01-2017)¨
 
2018-12-05 14:49:00.528 ERROR 65881 --- Ý7445-Acceptor-0¨ org.apache.tomcat.util.net.NioEndpoint   : Socket accept failed
 
java.io.IOException: EDC5122I Input/output error.
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~Ýna:1.8.0¨
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:478) ~Ýna:1.8.0¨
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:287) ~Ýna:1.8.0¨
	at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:455) ~Ýtomcat-embed-core-8.5.32.jar!/:8.5.32¨
	at java.lang.Thread.run(Thread.java:795) Ýna:2.9 (09-01-2017)¨
 
2018-12-05 14:49:00.550 ERROR 16843103 --- Ý7446-Acceptor-0¨ org.apache.tomcat.util.net.NioEndpoint   : Socket accept failed
 
java.io.IOException: EDC5122I Input/output error.
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~Ýna:1.8.0¨
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:478) ~Ýna:1.8.0¨
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:287) ~Ýna:1.8.0¨
	at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:482) ~Ýtomcat-coyote-8.5.33.jar!/:8.5.33¨
	at java.lang.Thread.run(Thread.java:795) Ýna:2.9 (09-01-2017)¨
 
2018-12-05 14:49:02.134 ERROR 65881 --- Ý7445-Acceptor-0¨ org.apache.tomcat.util.net.NioEndpoint   : Socket accept failed
 
java.io.IOException: EDC5122I Input/output error.
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~Ýna:1.8.0¨
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:478) ~Ýna:1.8.0¨
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:287) ~Ýna:1.8.0¨
	at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:455) ~Ýtomcat-embed-core-8.5.32.jar!/:8.5.32¨
	at java.lang.Thread.run(Thread.java:795) Ýna:2.9 (09-01-2017)¨
 
2018-12-05 14:49:02.155 ERROR 16843103 --- Ý7446-Acceptor-0¨ org.apache.tomcat.util.net.NioEndpoint   : Socket accept failed
 
java.io.IOException: EDC5122I Input/output error.
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~Ýna:1.8.0¨
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:478) ~Ýna:1.8.0¨
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:287) ~Ýna:1.8.0¨
	at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:482) ~Ýtomcat-coyote-8.5.33.jar!/:8.5.33¨
	at java.lang.Thread.run(Thread.java:795) Ýna:2.9 (09-01-2017)¨
 
2018-12-05 14:49:03.740 ERROR 65881 --- Ý7445-Acceptor-0¨ org.apache.tomcat.util.net.NioEndpoint   : Socket accept failed
 
java.io.IOException: EDC5122I Input/output error.
	at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method) ~Ýna:1.8.0¨
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:478) ~Ýna:1.8.0¨
	at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:287) ~Ýna:1.8.0¨
	at org.apache.tomcat.util.net.NioEndpoint$Acceptor.run(NioEndpoint.java:455) ~Ýtomcat-embed-core-8.5.32.jar!/:8.5.32¨
	at java.lang.Thread.run(Thread.java:795) Ýna:2.9 (09-01-2017)¨

```

I am not able to issue ```/P zowesvr```, as for some reason that won't shutdown Zowe on my system, so I cancel the main task, which leaves behind ZOWESVR3, which I then have to force cancel.

**Ideal resolution:**
This suggests that some part of Zowe, survived the TCPIP recycle, and other parts didnt. It would be wonderful if Zowe could handle the TCPIP recycle seamlessly, however if it can't then the persistently looping error will cause issues with spool space(This log, over a 24 hour period, where Zowe had almost no use, has grown to almost 13.1MB).

Please see the complete log attached.[joblog.txt](https://github.com/zowe/explorer-server/files/2649304/joblog.txt)

**Comment by stevenhorsman** [comment]
This is not an issues against the explorer-server, as the errors listed are tomcat problems. I suggest that this is re-checked with the 1.0 release candidate and raising the issues against the correct services
